version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - postgres


  app_test:
    image: gradle:8.2.1-jdk17
    container_name: springboot_test
    working_dir: /home/gradle/project
    volumes:
      - .:/home/gradle/project
    command: ["./gradlew", "test"]
    environment:
      DB_HOST: postgres_test
      DB_PORT: 5432
      DB_NAME: mytestdatabase
      DB_USERNAME: mytestuser
      DB_PASSWORD: mytestpassword
    depends_on:
      - postgres_test
    profiles:
      - test

  postgres_test:
    image: postgres:15-alpine
    container_name: postgres_db_test
    environment:
      POSTGRES_DB: mytestdatabase
      POSTGRES_USER: mytestuser
      POSTGRES_PASSWORD: mytestpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
