spring:
    application:
      name: rem.homework
    datasource:
      username: ${db.username}
      password: ${db.password}
      url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      hibernate:
        ddl-auto: create
    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml

